services:
  mysql:
    image: mysql:8.0
    container_name: tq_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: spms
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: tq_web
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root@mysql:3306/spms
    command: npm start

volumes:
  mysql_data:
